version: '3.9'

services:
  app:
    build:
      args:
        USERNAME: node
        VARIANT: 20-bookworm
    volumes:
      - ..:/workspace:cached
      - node-modules:/workspace/node_modules
      - pnpm-store:/workspace/.pnpm-store
    command: sleep infinity

volumes:
  node-modules:
  pnpm-store:
